In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_v9.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,31518,CA-2012-169397,2012-12-24,2012-12-27,First Class,JB-15925,Joni Blumstein,Consumer,Dublin,Ohio,...,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,19.776,4,0.7,-13.8432,0.79,Medium
1,6224,US-2011-144729,2011-07-21,2011-07-24,First Class,SS-20140,Saphhira Shifley,Corporate,San Miguelito,Panama,...,OFF-FA-10002247,Office Supplies,Fasteners,"OIC Paper Clips, Bulk Pack",11.544,2,0.4,-5.216,0.97,medium
2,15333,IT-2014-4749412,2014-09-18,2014-09-23,Standard Class,MB-18085,Mick Brown,Unknown,Birmingham,England,...,OFF-AR-10003113,Office Supplies,Art,"Binney & Smith Pens, Blue",29.85,5,0.5,-4.8,3.71,medium
3,49259,NI-2013-4420,2013-04-10,2013-10-10,Standard Class,MP-7965,Michael Paige,Corporate,Lagos,Lagos,...,OFF-AVE-10004512,Office Supplies,Binders,"Avery Hole Reinforcements, Economy",1.323,1,0.7,-3.087,0.06,Medium
4,24199,IN-2014-14423,2014-10-29,2014-10-30,First Class,DL-12925,Daniel Lacy,Consumer,Kendari,Sulawesi Tenggara,...,FUR-FU-10002362,Furniture,Furnishings,"Advantus Door Stop, Black",131.4876,4,0.27,25.1676,NaN,HIGH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51365,17526,ES-2014-2057259,2014-08-02,2014-08-05,First Class,PB-19150,Philip Brown,Consumer,Cagnes-Sur-Mer,Provence-Alpes-Cote d'Azur,...,OFF-PA-10002616,Office Supplies,Paper,"Green Bar Parchment Paper, Multicolor",108.54,6,0.0,34.56,11.76,MEDIUM
51366,36055,CA-2011-121573,2011-11-03,2011-07-11,Standard Class,SG-20605,Speros Goranitis,Consumer,New York City,New York,...,TEC-PH-10000984,Technology,Phone,Panasonic KX-TG9471B,783.96,4,0.0,219.5088,64.42,High
51367,43576,TU-2011-9190,2011-12-23,2011-12-28,Second Class,CM-1830,Cari Macintyre,Corporate,Corum,Corum,...,OFF-KIT-10002357,Office Supplies,Appliances,"KitchenAid Blender, White",$39.84,1,0.6,-12.96,5.84,Medium
51368,22403,IN-2013-35388,2013-08-07,2013-08-11,Standard Class,IM-15055,Unknown,Consumer,Jakarta,Jakarta,...,OFF-AR-10000058,Office Supplies,Art,"Stanley Canvas, Water Color",38.4345,1,0.27,3.6645,2.96,Medium
51369,12513,ES-2011-1222857,2011-09-30,2011-10-04,Standard Class,DP-13000,Darren Powers,Consumer,Toulouse,Midi-Pyrenees,...,FUR-CH-10003248,Furniture,Chairs,"SAFCO Bag Chairs, Black",169.236,9,0.6,-182.034,17.34,High

In [3]:
df['State'].info()

<class 'pandas.Series'>
RangeIndex: 51370 entries, 0 to 51369
Series name: State
Non-Null Count  Dtype
--------------  -----
50383 non-null  str
dtypes: str(1)
memory usage: 401.5 KB

In [4]:
df['State'] = df['State'].str.lstrip().str.rstrip().str.title()

In [5]:
df['State'].value_counts()

State
California       1952
England          1466
New York         1094
Texas             960
Ile-De-France     957
                 ...
Ibb                 1
Novgorod            1
La Rioja            1
Savanes             1
Yevrey              1
Name: count, Length: 1099, dtype: int64

In [6]:
df['State'].drop_duplicates()

0                     Ohio
1                   Panama
2                  England
3                    Lagos
4        Sulawesi Tenggara
               ...
46857                  Ibb
47796             Novgorod
48100             La Rioja
48290              Savanes
50263               Yevrey
Name: State, Length: 1100, dtype: str

In [14]:
df['State'].str.contains(r'[0-9]').sum()

np.int64(0)

In [13]:
df['State'].isna().sum()

np.int64(0)

In [12]:
df[df['State'] == 'Unknown' ]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
31,29547,ID-2014-35073,2014-04-09,2014-04-12,First Class,DK-13150,David Kendrick,Corporate,Jakarta,Unknown,...,OFF-ST-10000948,Office Supplies,Storage,"Fellowes Box, Blue",49.0032,3,0.17,18.8532,2.57,Medium
175,14873,IT-2014-2277753,2014-01-14,2014-01-16,Second Class,AG-10765,Anthony Garverick,Home Office,Florence,Unknown,...,FUR-CH-10001039,Furniture,Chairs,"Harbour Creations Rocking Chair, Adjustable",358.992,6,0.6,-251.388,30.31,Medium
188,15487,ES-2012-1158066,2012-09-08,2012-09-10,Second Class,BM-11575,Brendan Murry,Corporate,Mulhouse,Unknown,...,OFF-ST-10001648,Office Supplies,Storage,"Tenex Shelving, Blue",98.388,2,0.1,-5.472,23.81,Critical
191,42631,TU-2013-3960,2013-06-22,2013-06-26,Second Class,DB-3405,Denny Blanton,Unknown,Istanbul,Unknown,...,FUR-HAR-10002697,Furniture,Chairs,"Harbour Creations Executive Leather Armchair, ...",188.472,1,0.6,-51.858,17.8,High
223,2923,MX-2014-151218,2014-04-16,2014-04-18,First Class,RE-19405,Ricardo Emerson,Consumer,San Salvador,Unknown,...,FUR-FU-10004800,Furniture,Furnishings,"Eldon Stacking Tray, Black",21.0,1,0.0,3.36,4.92,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50998,36753,CA-2014-130631,2014-12-30,2015-01-03,Standard Class,BS-11755,Bruce Stewart,Consumer,Edmonds,Unknown,...,OFF-FA-10000089,Office Supplies,Fasteners,Acco Glide Clips,19.6,two,0.0,9.604,0.71,Medium
51014,6698,MX-2014-144722,2014-06-06,2014-11-06,Standard Class,BS-11800,Unknown,Home Office,Sapucaia Do Sul,Unknown,...,OFF-EN-10001533,Office Supplies,Envelopes,"Kraft Mailers, with clear poly window",247.14,9,0.0,14.76,17.84,Medium
51020,5402,MX-2011-149027,2011-10-22,2011-10-27,Standard Class,AO-10810,Anthony O'Donnell,Corporate,Santiago,Unknown,...,OFF-ST-10001954,Office Supplies,Storage,"Rogers Shelving, Wire Frame",163.2,4,0.0,45.68,12.32,Medium
51217,42807,AJ-2012-7720,2012-11-02,2012-11-05,First Class,SG-10890,Susan Gilcrest,Corporate,Baku,Unknown,...,OFF-CAR-10001577,Office Supplies,Binders,"Cardinal Binding Machine, Economy",199.08,4,0.0,55.68,7.36,High
51285,1105,US-2012-142699,2012-01-28,2012-02-04,Standard Class,BS-11365,Bill Shonely,Corporate,Portmore,Unknown,...,FUR-FU-10000490,Furniture,Furnishings,"Eldon Light Bulb, Erganomic",31.76,2,0.0,8.56,1.64,Medium

In [11]:
df['State'] = df['State'].fillna('Unknown')

In [15]:
df['State'].info()

<class 'pandas.Series'>
RangeIndex: 51370 entries, 0 to 51369
Series name: State
Non-Null Count  Dtype
--------------  -----
51370 non-null  str
dtypes: str(1)
memory usage: 401.5 KB

In [16]:
df.to_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_v10.csv',index=False)