In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_v8.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,31518,CA-2012-169397,2012-12-24,2012-12-27,First Class,JB-15925,Joni Blumstein,Consumer,Dublin,Ohio,...,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,19.776,4,0.7,-13.8432,0.79,Medium
1,6224,US-2011-144729,2011-07-21,2011-07-24,First Class,SS-20140,Saphhira Shifley,Corporate,San Miguelito,Panama,...,OFF-FA-10002247,Office Supplies,Fasteners,"OIC Paper Clips, Bulk Pack",11.544,2,0.4,-5.216,0.97,medium
2,15333,IT-2014-4749412,2014-09-18,2014-09-23,Standard Class,MB-18085,Mick Brown,Unknown,Birmingham,England,...,OFF-AR-10003113,Office Supplies,Art,"Binney & Smith Pens, Blue",29.85,5,0.5,-4.8,3.71,medium
3,49259,NI-2013-4420,2013-04-10,2013-10-10,Standard Class,MP-7965,Michael Paige,Corporate,Lagos,Lagos,...,OFF-AVE-10004512,Office Supplies,Binders,"Avery Hole Reinforcements, Economy",1.323,1,0.7,-3.087,0.06,Medium
4,24199,IN-2014-14423,2014-10-29,2014-10-30,First Class,DL-12925,Daniel Lacy,Consumer,Kendari,Sulawesi Tenggara,...,FUR-FU-10002362,Furniture,Furnishings,"Advantus Door Stop, Black",131.4876,4,0.27,25.1676,NaN,HIGH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51365,17526,ES-2014-2057259,2014-08-02,2014-08-05,First Class,PB-19150,Philip Brown,Consumer,Cagnes-sur-Mer,Provence-Alpes-Cote d'Azur,...,OFF-PA-10002616,Office Supplies,Paper,"Green Bar Parchment Paper, Multicolor",108.54,6,0.0,34.56,11.76,MEDIUM
51366,36055,CA-2011-121573,2011-11-03,2011-07-11,Standard Class,SG-20605,Speros Goranitis,Consumer,New York City,New York,...,TEC-PH-10000984,Technology,Phone,Panasonic KX-TG9471B,783.96,4,0.0,219.5088,64.42,High
51367,43576,TU-2011-9190,2011-12-23,2011-12-28,Second Class,CM-1830,Cari Macintyre,Corporate,Corum,Corum,...,OFF-KIT-10002357,Office Supplies,Appliances,"KitchenAid Blender, White",$39.84,1,0.6,-12.96,5.84,Medium
51368,22403,IN-2013-35388,2013-08-07,2013-08-11,Standard Class,IM-15055,Unknown,Consumer,Jakarta,Jakarta,...,OFF-AR-10000058,Office Supplies,Art,"Stanley Canvas, Water Color",38.4345,1,0.27,3.6645,2.96,Medium
51369,12513,ES-2011-1222857,2011-09-30,2011-10-04,Standard Class,DP-13000,Darren Powers,Consumer,Toulouse,Midi-Pyrenees,...,FUR-CH-10003248,Furniture,Chairs,"SAFCO Bag Chairs, Black",169.236,9,0.6,-182.034,17.34,High

In [3]:
df['City'].info()

<class 'pandas.Series'>
RangeIndex: 51370 entries, 0 to 51369
Series name: City
Non-Null Count  Dtype
--------------  -----
50728 non-null  str
dtypes: str(1)
memory usage: 401.5 KB

In [7]:
df['City'].drop_duplicates()

0                 Dublin
1          San Miguelito
2             Birmingham
3                  Lagos
4                Kendari
              ...
50633    Charlottesville
50668             Passau
50901            Sagunto
51218      Saint-Laurent
51316            Zaoyang
Name: City, Length: 3636, dtype: str

In [6]:
df['City'] = df['City'].str.lstrip().str.rstrip().str.title()

In [8]:
df['City'].value_counts()

City
New York City      900
Los Angeles        731
Philadelphia       526
San Francisco      496
Santo Domingo      435
                  ...
Charlottesville      1
Passau               1
Sagunto              1
Saint-Laurent        1
Zaoyang              1
Name: count, Length: 3635, dtype: int64

In [19]:
df['City'].str.contains(r'[0-9]')

0        False
1        False
2        False
3        False
4        False
         ...
51365    False
51366    False
51367    False
51368    False
51369    False
Name: City, Length: 51370, dtype: bool

In [10]:
df[df['City'].str.contains(r'[0-9]')]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, City, State, Country, Postal Code, Market, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Cost, Order Priority]
Index: []

[0 rows x 24 columns]

In [18]:
df['City'].isna().sum()

np.int64(0)

In [17]:
df.loc[df['City'] == 'Unknown']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
67,51051,IR-2011-1690,2011-07-29,2011-08-03,Standard Class,JL-5130,Jack Lebron,Consumer,Unknown,Ardabil,...,OFF-SME-10004370,Office Supplies,Storage,"Smead File Cart, Blue",127.47,1,0.0,1.26,9.84,Medium
291,34837,CA-2011-158771,2011-05-09,2011-05-09,Same Day,SB-20290,Sean Braxton,Corporate,Unknown,Kentucky,...,OFF-PA-10002689,Office Supplies,Paper,Weyerhaeuser First Choice Laser/Copy Paper (20...,45.36,7,0.0,21.7728,2.47,Medium
301,32262,CA-2014-135279,2014-04-10,2014-04-12,First Class,BS-11800,Bryan Spruell,Home Office,Unknown,New York,...,OFF-AR-10004344,Office Supplies,Art,Bulldog Vacuum Base Pencil Sharpener,35.97,3,0.0,9.7119,8.05,High
371,43048,CA-2011-3390,2011-09-21,2011-09-24,Second Class,AS-240,Alan Shonely,Consumer,Unknown,Ontario,...,OFF-SME-10004754,Office Supplies,Labels,"Smead Round Labels, Adjustable",4.8,1,0.0,1.44,0.35,Medium
469,15034,ES-2012-4920028,2012-12-04,2012-10-12,Standard Class,VP-21730,Victor Preis,Home Office,Unknown,Catalonia,...,OFF-AR-10002037,OFFICE SUPPLIES,Art,"Stanley Sketch Pad, Fluorescent",274.14,6,0.0,43.74,40.09,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50893,18744,ES-2012-3446562,2012-11-24,2012-11-29,Standard Class,JE-16165,Justin Ellison,Corporate,Unknown,Baden-Württemberg,...,FUR-FU-10004955,Furniture,Furnishings,"Tenex Door Stop, Durable",204.6,5,0.0,26.55,15.62,Medium
50937,28447,IN-2014-14850,2014-12-26,2014-12-31,Standard Class,SS-20590,Sonia Sunley,Consumer,Unknown,Yogyakarta,...,OFF-ST-10002650,office supplies,Storage,"Fellowes Lockers, Wire Frame",342.624,2,0.17,61.884,17.23,MEDIUM
51239,42405,TU-2013-7880,2013-09-19,2013-09-23,Standard Class,AA-315,Alex Avila,Consumer,Unknown,Bursa,...,FUR-IKE-10003015,Furniture,Bookcases,"Ikea Library with Doors, Mobile",146.364,1,0.6,-201.276,9.77,Medium
51267,17830,ES-2014-3014144,2014-04-06,2014-04-08,First Class,BS-11755,Bruce Stewart,Consumer,Unknown,Provence-Alpes-Cote d'Azur,...,OFF-ST-10001413,office supplies,Storage,"Rogers Folders, Blue",110.484,4,0.1,-9.876,27.86,High
51336,23488,ID-2014-35521,2014-06-16,2014-06-18,Second Class,MS-17770,Maxwell Schwartz,Consumer,Unknown,Seoul,...,OFF-BI-10000590,Office Supplies,Binders,"Wilson Jones Binding Machine, Clear",96.84,4,0.5,-60.12,12.87,high

In [16]:
df['City'] = df['City'].fillna('Unknown')

In [20]:
df.to_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_v9.csv',index=False)