In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_v10.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,31518,CA-2012-169397,2012-12-24,2012-12-27,First Class,JB-15925,Joni Blumstein,Consumer,Dublin,Ohio,...,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,19.776,4,0.7,-13.8432,0.79,Medium
1,6224,US-2011-144729,2011-07-21,2011-07-24,First Class,SS-20140,Saphhira Shifley,Corporate,San Miguelito,Panama,...,OFF-FA-10002247,Office Supplies,Fasteners,"OIC Paper Clips, Bulk Pack",11.544,2,0.4,-5.216,0.97,medium
2,15333,IT-2014-4749412,2014-09-18,2014-09-23,Standard Class,MB-18085,Mick Brown,Unknown,Birmingham,England,...,OFF-AR-10003113,Office Supplies,Art,"Binney & Smith Pens, Blue",29.85,5,0.5,-4.8,3.71,medium
3,49259,NI-2013-4420,2013-04-10,2013-10-10,Standard Class,MP-7965,Michael Paige,Corporate,Lagos,Lagos,...,OFF-AVE-10004512,Office Supplies,Binders,"Avery Hole Reinforcements, Economy",1.323,1,0.7,-3.087,0.06,Medium
4,24199,IN-2014-14423,2014-10-29,2014-10-30,First Class,DL-12925,Daniel Lacy,Consumer,Kendari,Sulawesi Tenggara,...,FUR-FU-10002362,Furniture,Furnishings,"Advantus Door Stop, Black",131.4876,4,0.27,25.1676,NaN,HIGH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51365,17526,ES-2014-2057259,2014-08-02,2014-08-05,First Class,PB-19150,Philip Brown,Consumer,Cagnes-Sur-Mer,Provence-Alpes-Cote D'Azur,...,OFF-PA-10002616,Office Supplies,Paper,"Green Bar Parchment Paper, Multicolor",108.54,6,0.0,34.56,11.76,MEDIUM
51366,36055,CA-2011-121573,2011-11-03,2011-07-11,Standard Class,SG-20605,Speros Goranitis,Consumer,New York City,New York,...,TEC-PH-10000984,Technology,Phone,Panasonic KX-TG9471B,783.96,4,0.0,219.5088,64.42,High
51367,43576,TU-2011-9190,2011-12-23,2011-12-28,Second Class,CM-1830,Cari Macintyre,Corporate,Corum,Corum,...,OFF-KIT-10002357,Office Supplies,Appliances,"KitchenAid Blender, White",$39.84,1,0.6,-12.96,5.84,Medium
51368,22403,IN-2013-35388,2013-08-07,2013-08-11,Standard Class,IM-15055,Unknown,Consumer,Jakarta,Jakarta,...,OFF-AR-10000058,Office Supplies,Art,"Stanley Canvas, Water Color",38.4345,1,0.27,3.6645,2.96,Medium
51369,12513,ES-2011-1222857,2011-09-30,2011-10-04,Standard Class,DP-13000,Darren Powers,Consumer,Toulouse,Midi-Pyrenees,...,FUR-CH-10003248,Furniture,Chairs,"SAFCO Bag Chairs, Black",169.236,9,0.6,-182.034,17.34,High

In [3]:
df['Country'].info()

<class 'pandas.Series'>
RangeIndex: 51370 entries, 0 to 51369
Series name: Country
Non-Null Count  Dtype
--------------  -----
51370 non-null  str
dtypes: str(1)
memory usage: 401.5 KB

In [6]:
df['Country'].drop_duplicates()

0            United States
1                   Panama
2           United Kingdom
3                  Nigeria
4                Indonesia
               ...
20897              Armenia
21023    Equatorial Guinea
23149           Mauritania
29453          South Sudan
43320             Slovenia
Name: Country, Length: 154, dtype: str

In [5]:
df['Country'] = df['Country'].str.lstrip().str.rstrip().str.title()

In [32]:
df['Country'].value_counts()

Country
United States Of America    10014
Australia                    2842
France                       2830
Mexico                       2651
Germany                      2069
                            ...
Eritrea                         2
Burundi                         2
Chad                            2
Bahrain                         2
South Sudan                     2
Name: count, Length: 147, dtype: int64

In [8]:
df[df['Country'] == 'Unknown']

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, City, State, Country, Postal Code, Market, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Cost, Order Priority]
Index: []

[0 rows x 24 columns]

In [9]:
df[df['Country'].isna()]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, City, State, Country, Postal Code, Market, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Cost, Order Priority]
Index: []

[0 rows x 24 columns]

In [25]:
df['Country'] = df['Country'].str.lstrip().str.rstrip().str.title()

In [31]:
for x in df['Country'].drop_duplicates():
    print(x)

United States Of America
Panama
United Kingdom
Nigeria
Indonesia
India
Germany
China
Cuba
Colombia
Mexico
Australia
Brazil
El Salvador
Democratic Republic Of The Congo
Argentina
Honduras
Denmark
Pakistan
Philippines
Spain
Zambia
Bolivia
Haiti
Belgium
New Zealand
Nicaragua
Libya
France
Morocco
Mozambique
Sweden
Iran
Albania
Thailand
Russia
South Africa
Egypt
Austria
Switzerland
Ireland
South Korea
Vietnam
Italy
Kyrgyzstan
Turkey
Tanzania
Algeria
Dominican Republic
Romania
Cote D'Ivoire
Malaysia
Czech Republic
Poland
Canada
Japan
Sierra Leone
Georgia
Bangladesh
Guatemala
Zimbabwe
Madagascar
Venezuela
Chile
Belarus
Cambodia
Netherlands
Benin
Paraguay
Guinea
Senegal
Ukraine
Kenya
Iraq
Peru
Saudi Arabia
Norway
Great Britain
Singapore
Djibouti
Togo
Kazakhstan
Yemen
Mali
Hungary
Sudan
Finland
Lithuania
Hong Kong
Israel
Myanmar (Burma)
Bulgaria
Slovakia
Trinidad And Tobago
Martinique
Gabon
Uganda
Ghana
Mongolia
Jordan
Niger
Jamaica
Syria
Afghanistan
United Arab Emirates
Portugal
Ecuador
Angola
Cameroon
Rwanda
Eritrea
Tunisia
Barbados
Lebanon
Somalia
Uruguay
Moldova
Uzbekistan
Qatar
Burundi
Croatia
Guadeloupe
Liberia
Lesotho
Turkmenistan
Papua New Guinea
Ethiopia
Guinea-Bissau
Azerbaijan
Namibia
Central African Republic
Estonia
Nepal
Bosnia And Herzegovina
Taiwan
Republic Of The Congo
Macedonia
Sri Lanka
Chad
Bahrain
Tajikistan
Montenegro
Armenia
Equatorial Guinea
Mauritania
South Sudan
Slovenia

In [28]:
df['Country'] = df['Country'].replace(
    {
        'U.S.A.':'United States Of America',
        'U.K.':'United Kingdom',
        'Usa':'United States Of America',
        'Uk':'United Kingdom',
        'Swaziland':'Switzerland',
        'United States':'United States Of America',
    }
)

In [30]:
df['Country'] = df['Country'].replace('Us','United States Of America')

In [34]:
df['Country'].isna().sum()

np.int64(0)

In [35]:
df.to_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_v11.csv',index=False)