In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_v2.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,31518,CA-2012-169397,24-12-2012,27-12-2012,First Class,JB-15925,Joni Blumstein,Consumer,Dublin,Ohio,...,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,19.776,4,0.7,-13.8432,0.79,Medium
1,6224,US-2011-144729,21-07-2011,24-07-2011,First Class,SS-20140,Saphhira Shifley,Corporate,San Miguelito,Panama,...,OFF-FA-10002247,Office Supplies,Fasteners,"OIC Paper Clips, Bulk Pack",11.544,2,0.4,-5.216,0.97,medium
2,15333,IT-2014-4749412,18-09-2014,23-09-2014,Standard Class,MB-18085,Mick Brown,-,Birmingham,England,...,OFF-AR-10003113,Office Supplies,Art,"Binney & Smith Pens, Blue",29.85,5,0.5,-4.8,3.71,medium
3,49259,NI-2013-4420,"Apr 10, 2013",10/10/2013,Standard Class,MP-7965,Michael Paige,Corporate,Lagos,Lagos,...,OFF-AVE-10004512,Office Supplies,Binders,"Avery Hole Reinforcements, Economy",1.323,1,0.7,-3.087,0.06,Medium
4,24199,IN-2014-14423,29-10-2014,30-10-2014,First Class,DL-12925,Daniel Lacy,Consumer,Kendari,Sulawesi Tenggara,...,FUR-FU-10002362,Furniture,Furnishings,"Advantus Door Stop, Black",131.4876,4,0.27,25.1676,NaN,HIGH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51365,17526,ES-2014-2057259,2/8/2014,5/8/2014,First Class,PB-19150,Philip Brown,Consumer,Cagnes-sur-Mer,Provence-Alpes-Cote d'Azur,...,OFF-PA-10002616,Office Supplies,Paper,"Green Bar Parchment Paper, Multicolor",108.54,6,0.0,34.56,11.76,MEDIUM
51366,36055,CA-2011-121573,3/11/2011,"Jul 11, 2011",Standard Class,SG-20605,Speros Goranitis,Consumer,New York City,New York,...,TEC-PH-10000984,Technology,Phone,Panasonic KX-TG9471B,783.96,4,0.0,219.5088,64.42,High
51367,43576,TU-2011-9190,23-12-2011,28-12-2011,Second Class,CM-1830,Cari MacIntyre,Corporate,Corum,Corum,...,OFF-KIT-10002357,Office Supplies,Appliances,"KitchenAid Blender, White",$39.84,1,0.6,-12.96,5.84,Medium
51368,22403,IN-2013-35388,7/8/2013,11/8/2013,Standard Class,IM-15055,NaN,Consumer,Jakarta,Jakarta,...,OFF-AR-10000058,Office Supplies,Art,"Stanley Canvas, Water Color",38.4345,1,0.27,3.6645,2.96,Medium
51369,12513,ES-2011-1222857,30-09-2011,2011-04-10,Standard Class,DP-13000,Darren Powers,Consumer,Toulouse,Midi-Pyrenees,...,FUR-CH-10003248,Furniture,Chairs,"SAFCO Bag Chairs, Black",169.236,9,0.6,-182.034,17.34,High

In [3]:
df['Order Date'].info()

<class 'pandas.Series'>
RangeIndex: 51370 entries, 0 to 51369
Series name: Order Date
Non-Null Count  Dtype
--------------  -----
51370 non-null  str
dtypes: str(1)
memory usage: 401.5 KB

In [17]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='mixed', dayfirst=True, errors='coerce')

0       2012-12-24
1       2011-07-21
2       2014-09-18
3       2013-04-10
4       2014-10-29
           ...
51365   2014-08-02
51366   2011-11-03
51367   2011-12-23
51368   2013-08-07
51369   2011-09-30
Name: Order Date, Length: 51370, dtype: datetime64[us]

In [18]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='mixed', dayfirst=True, errors='coerce')

In [20]:
df[df['Order Date'].isna()]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
269,32092,CA-2014-151428,NaT,27-09-2014,Standard Class,RH-19495,Rick Hansen,CONSUMER,Rochester,Minnesota,...,OFF-BI-10000546,Office Supplies,Binders,Avery Durable Binders,20.16,7,0.0,9.8784,1.3,Medium
802,18648,ES-2013-4986805,NaT,25-09-2013,First Class,JK-15205,Jamie Kunitz,Consumer,Argenteuil,Ile-de-France,...,OFF-FA-10004878,Office Supplies,Fasteners,"Stockwell Clamps, Bulk Pack",131.88,7,0.0,10.5,13.27,Medium
1009,25777,IN-2014-22228,NaT,10/11/2014,Second Class,EJ-13720,Ed Jacobs,Consumer,Brisbane,Queensland,...,FUR-CH-10000351,Furniture,Chairs,"Novimex Chairmat, Set of Two",369.117,7,0.1,110.607,51.63,Medium
1155,956,MX-2014-102064,NaT,28-09-2014,STANDARD CLASS,EH-14005,Erica Hernandez,Home Office,Uruguaiana,Rio Grande do Sul,...,OFF-ST-10002233,OFFICE SUPPLIES,Storage,"Smead Trays, Single Width",64.68,2,0.0,23.92,3.86,Medium
2381,43398,GH-2012-2610,NaT,19-08-2012,Second Class,RE-9450,Richard Eichhorn,NaN,Accra,Greater Accra,...,FUR-SAF-10000265,Furniture,Bookcases,"Safco Library with Doors, Metal",389.25,1,0.0,66.15,55.87,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48774,34374,CA-2011-143903,NaT,24-07-2011,Standard Class,KM-16375,UNKNOWN,Home Office,Dallas,Texas,...,FUR-CH-10002024,Furnture,Chairs,HON 5400 Series Task Chairs for Big and Tall,981.372,2,0.3,-140.196,85.32,High
48860,9785,MX-2012-166485,NaT,14-09-2012,Second Class,SC-20845,Sung Chung,Consumer,Santa Clara,Villa Clara,...,OFF-EN-10003636,Office Supplies,Envelopes,"Jiffy Peel and Seal, Security-Tint",29.88,2,0.0,7.44,-,Critical
49916,13501,ES-2014-5759001,NaT,17-12-2014,standard class,JR-16210,Justin Ritter,Corporate,?,Ile-de-France,...,OFF-LA-10003058,Office Supplies,Labels,"Novimex Legal Exhibit Labels, Adjustable",16.74,2,0.0,1.14,1.59,Medium
50195,26147,IN-2011-67616,NaT,20-12-2011,Second Class,NC-18625,Noah Childs,Corporate,Wollongong,New South Wales,...,OFF-SU-10000954,Office Supplies,Supplies,"Acme Scissors, High Speed",160.272,7,0.1,37.212,8.81,Medium
51044,14185,IT-2013-2494049,NaT,28-06-2013,Standard Class,JH-15430,Jennifer Halladay,Consumer,Alphen aan den Rijn,South Holland,...,TEC-CO-10002981,Technology,Copiers,"HP Wireless Fax, High-Speed",896.025,5,0.5,-35.925,15.83,Medium

In [21]:
df['Order Date'] = df['Order Date'].fillna(df['Order Date'].ffill())

In [22]:
df['Order Date'].isna().sum()

np.int64(0)

In [23]:
df.to_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_v3.csv',index=False)