In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_v18.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,31518,CA-2012-169397,2012-12-24,27-12-2012,First Class,JB-15925,Joni Blumstein,Consumer,Dublin,Ohio,...,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,19.7760,4,0.70,-13.84,0.79,Medium
1,6224,US-2011-144729,2011-07-21,24-07-2011,First Class,SS-20140,Saphhira Shifley,Corporate,San Miguelito,Panama,...,OFF-FA-10002247,Office Supplies,Fasteners,"Oic Paper Clips, Bulk Pack",11.5440,2,0.40,-5.22,0.97,medium
2,15333,IT-2014-4749412,2014-09-18,23-09-2014,Standard Class,MB-18085,Mick Brown,-,Birmingham,England,...,OFF-AR-10003113,Office Supplies,Art,"Binney & Smith Pens, Blue",29.8500,5,0.50,-4.80,3.71,medium
3,49259,NI-2013-4420,2013-04-10,10/10/2013,Standard Class,MP-7965,Michael Paige,Corporate,Lagos,Lagos,...,OFF-AVE-10004512,Office Supplies,Binders,"Avery Hole Reinforcements, Economy",1.3230,1,0.70,-3.09,0.06,Medium
4,24199,IN-2014-14423,2014-10-29,30-10-2014,First Class,DL-12925,Daniel Lacy,Consumer,Kendari,Sulawesi Tenggara,...,FUR-FU-10002362,Furniture,Furnishings,"Advantus Door Stop, Black",131.4876,4,0.27,25.17,NaN,HIGH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51365,17526,ES-2014-2057259,2014-08-02,5/8/2014,First Class,PB-19150,Philip Brown,Consumer,Cagnes-sur-Mer,Provence-Alpes-Cote d'Azur,...,OFF-PA-10002616,Office Supplies,Paper,"Green Bar Parchment Paper, Multicolor",108.5400,6,0.00,34.56,11.76,MEDIUM
51366,36055,CA-2011-121573,2011-11-03,"Jul 11, 2011",Standard Class,SG-20605,Speros Goranitis,Consumer,New York City,New York,...,TEC-PH-10000984,Technology,Phones,Panasonic Kx-Tg9471B,783.9600,4,0.00,219.51,64.42,High
51367,43576,TU-2011-9190,2011-12-23,28-12-2011,Second Class,CM-1830,Cari MacIntyre,Corporate,Corum,Corum,...,OFF-KIT-10002357,Office Supplies,Appliances,"Kitchenaid Blender, White",39.8400,1,0.60,-12.96,5.84,Medium
51368,22403,IN-2013-35388,2013-08-07,11/8/2013,Standard Class,IM-15055,NaN,Consumer,Jakarta,Jakarta,...,OFF-AR-10000058,Office Supplies,Art,"Stanley Canvas, Water Color",38.4345,1,0.27,3.66,2.96,Medium
51369,12513,ES-2011-1222857,2011-09-30,2011-04-10,Standard Class,DP-13000,Darren Powers,Consumer,Toulouse,Midi-Pyrenees,...,FUR-CH-10003248,Furniture,Chairs,"Safco Bag Chairs, Black",169.2360,9,0.60,-182.03,17.34,High

In [3]:
df['Shipping Cost'].info()

<class 'pandas.Series'>
RangeIndex: 51370 entries, 0 to 51369
Series name: Shipping Cost
Non-Null Count  Dtype
--------------  -----
50649 non-null  str
dtypes: str(1)
memory usage: 401.5 KB

In [4]:
df['Shipping Cost'].value_counts()

Shipping Cost
?          124
Unknown     91
-           88
0.86        75
1.26        71
          ...
20.98        1
141.27       1
$13.28       1
169.01       1
64.42        1
Name: count, Length: 11120, dtype: int64

In [6]:
df['Shipping Cost'].str.contains(r'[^0-9]',regex=True)

0         True
1         True
2         True
3         True
4        False
         ...
51365     True
51366     True
51367     True
51368     True
51369     True
Name: Shipping Cost, Length: 51370, dtype: bool

In [20]:
df[df['Shipping Cost'].str.contains(r'[^0-9.]',regex=True)]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, City, State, Country, Postal Code, Market, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Cost, Order Priority]
Index: []

[0 rows x 24 columns]

In [19]:
df['Shipping Cost'] = df['Shipping Cost'].str.replace(r'nan','')

In [21]:
df['Shipping Cost'] = pd.to_numeric(df['Shipping Cost'], errors='coerce')

In [25]:
df['Shipping Cost'].isna().sum()

np.int64(0)

In [24]:
df['Shipping Cost'] = df['Shipping Cost'].fillna(0)

In [26]:
df['Shipping Cost'].info()

<class 'pandas.Series'>
RangeIndex: 51370 entries, 0 to 51369
Series name: Shipping Cost
Non-Null Count  Dtype
--------------  -----
51370 non-null  float64
dtypes: float64(1)
memory usage: 401.5 KB

In [27]:
df.to_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_v19.csv',index=False)