In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_clean.csv')

df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,31518,CA-2012-169397,2012-12-24,27-12-2012,First Class,JB-15925,Joni Blumstein,Consumer,Dublin,Ohio,...,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,19.7760,4,0.70,-13.84,0.79,Medium
1,6224,US-2011-144729,2011-07-21,24-07-2011,First Class,SS-20140,Saphhira Shifley,Corporate,San Miguelito,Panama,...,OFF-FA-10002247,Office Supplies,Fasteners,"Oic Paper Clips, Bulk Pack",11.5440,2,0.40,-5.22,0.97,Medium
2,15333,IT-2014-4749412,2014-09-18,23-09-2014,Standard Class,MB-18085,Mick Brown,Unknown,Birmingham,England,...,OFF-AR-10003113,Office Supplies,Art,"Binney & Smith Pens, Blue",29.8500,5,0.50,-4.80,3.71,Medium
3,49259,NI-2013-4420,2013-04-10,10/10/2013,Standard Class,MP-7965,Michael Paige,Corporate,Lagos,Lagos,...,OFF-AVE-10004512,Office Supplies,Binders,"Avery Hole Reinforcements, Economy",1.3230,1,0.70,-3.09,0.06,Medium
4,24199,IN-2014-14423,2014-10-29,30-10-2014,First Class,DL-12925,Daniel Lacy,Consumer,Kendari,Sulawesi Tenggara,...,FUR-FU-10002362,Furniture,Furnishings,"Advantus Door Stop, Black",131.4876,4,0.27,25.17,0.00,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51365,17526,ES-2014-2057259,2014-08-02,5/8/2014,First Class,PB-19150,Philip Brown,Consumer,Cagnes-Sur-Mer,Provence-Alpes-Cote D'Azur,...,OFF-PA-10002616,Office Supplies,Paper,"Green Bar Parchment Paper, Multicolor",108.5400,6,0.00,34.56,11.76,Medium
51366,36055,CA-2011-121573,2011-11-03,"Jul 11, 2011",Standard Class,SG-20605,Speros Goranitis,Consumer,New York City,New York,...,TEC-PH-10000984,Technology,Phones,Panasonic Kx-Tg9471B,783.9600,4,0.00,219.51,64.42,High
51367,43576,TU-2011-9190,2011-12-23,28-12-2011,Second Class,CM-1830,Cari Macintyre,Corporate,Corum,Corum,...,OFF-KIT-10002357,Office Supplies,Appliances,"Kitchenaid Blender, White",39.8400,1,0.60,-12.96,5.84,Medium
51368,22403,IN-2013-35388,2013-08-07,11/8/2013,Standard Class,IM-15055,Unknown,Consumer,Jakarta,Jakarta,...,OFF-AR-10000058,Office Supplies,Art,"Stanley Canvas, Water Color",38.4345,1,0.27,3.66,2.96,Medium
51369,12513,ES-2011-1222857,2011-09-30,2011-04-10,Standard Class,DP-13000,Darren Powers,Consumer,Toulouse,Midi-Pyrenees,...,FUR-CH-10003248,Furniture,Chairs,"Safco Bag Chairs, Black",169.2360,9,0.60,-182.03,17.34,High

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51370 entries, 0 to 51369
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51370 non-null  int64
 1   Order ID        51370 non-null  str
 2   Order Date      51370 non-null  str
 3   Ship Date       51370 non-null  str
 4   Ship Mode       51370 non-null  str
 5   Customer ID     51370 non-null  str
 6   Customer Name   51336 non-null  str
 7   Segment         51370 non-null  str
 8   City            51351 non-null  str
 9   State           51339 non-null  str
 10  Country         51370 non-null  str
 11  Postal Code     51370 non-null  int64
 12  Market          51370 non-null  str
 13  Region          51370 non-null  str
 14  Product ID      51370 non-null  str
 15  Category        51370 non-null  str
 16  Sub-Category    51370 non-null  str
 17  Product Name    51370 non-null  str
 18  Sales           51370 non-null  float64
 19  Quantity        51370 non-null  int64
 20  Discount        51370 non-null  float64
 21  Profit          51370 non-null  float64
 22  Shipping Cost   51370 non-null  float64
 23  Order Priority  51370 non-null  str
dtypes: float64(4), int64(3), str(17)
memory usage: 9.4 MB

In [24]:
df.groupby(
    'State'
)[[
    'Sales',
    'Quantity',
    'Discount',
    'Profit'
]].agg(
    Total_Sales = ('Sales','sum'),
    Average_Sales = ('Sales','mean'),
    Minimum_Sales = ('Sales','min'),
    Maximum_Sales = ('Sales','max'),
	Sales_Standard_Deviation = ('Sales','std'),
    Number_of_Transaction = ('Sales','count'),

    Total_Units_Sold = ('Quantity','sum'),
    Average_Units_Sold = ('Quantity','mean'),
    Minimum_Quantity = ('Quantity','min'),
    Maximum_Quantity = ('Quantity','max'),
    Quantity_Standard_Deviation = ('Quantity','std'),

    Total_Discount = ('Discount','sum'),
    Average_Discount = ('Discount','mean'),
    Minimum_Discount = ('Discount','min'),
    Maximum_Discount = ('Discount','max'),
    Discount_Standard_Deviation = ('Discount','std'),

    Total_Profit = ('Profit','sum'),
    Average_Profit = ('Profit','mean'),
    Minimum_Profit = ('Profit','min'),
    Maximum_Profit = ('Profit','max'),
    Profit_Standard_Deviation = ('Profit','std')
).round(2)

,Total_Sales,Average_Sales,Minimum_Sales,Maximum_Sales,Sales_Standard_Deviation,Number_of_Transaction,Total_Units_Sold,Average_Units_Sold,Minimum_Quantity,Maximum_Quantity,...,Total_Discount,Average_Discount,Minimum_Discount,Maximum_Discount,Discount_Standard_Deviation,Total_Profit,Average_Profit,Minimum_Profit,Maximum_Profit,Profit_Standard_Deviation
State,,,,,,,,,,,,,,,,,,,,,
'Ajman,209.99,52.50,6.43,82.67,35.61,4,11,2.75,1,6,...,2.8,0.70,0.7,0.7,0.00,-332.71,-83.18,-157.09,-11.57,59.69
'Amman,7072.77,181.35,6.78,1054.02,240.07,39,102,2.62,1,8,...,0.0,0.00,0.0,0.0,0.00,1779.93,45.64,0.00,337.26,66.86
'Asir,1603.50,200.44,13.38,639.00,222.59,8,20,2.50,1,6,...,0.0,0.00,0.0,0.0,0.00,310.65,38.83,3.21,106.47,39.69
Abia,969.35,44.06,3.38,196.27,60.51,22,49,2.23,1,14,...,14.7,0.67,0.0,0.7,0.15,-1333.08,-60.59,-376.06,-6.81,89.25
Abruzzi,6923.46,364.39,35.52,2927.28,710.14,19,80,4.21,1,9,...,1.2,0.06,0.0,0.4,0.15,991.02,52.16,-32.58,421.20,98.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zinder,362.73,90.68,23.25,231.84,96.64,4,15,3.75,1,6,...,0.0,0.00,0.0,0.0,0.00,122.28,30.57,4.86,71.76,29.98
Zulia,4172.96,119.23,1.96,1054.02,182.81,35,146,4.17,1,13,...,14.0,0.40,0.4,0.4,0.00,-990.51,-28.30,-316.28,24.82,60.78
Zürich,11329.68,354.05,17.88,2380.50,478.94,32,128,4.00,1,9,...,0.0,0.00,0.0,0.0,0.00,3358.98,104.97,0.45,952.20,189.23
Iauliai,96.56,24.14,7.91,49.84,18.18,4,13,3.25,1,6,...,2.8,0.70,0.7,0.7,0.00,-164.74,-41.18,-103.16,-13.21,41.66
Ilina,60.12,30.06,28.98,31.14,1.53,2,4,2.00,2,2,...,0.0,0.00,0.0,0.0,0.00,18.84,9.42,9.30,9.54,0.17