In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_clean.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,31518,CA-2012-169397,2012-12-24,27-12-2012,First Class,JB-15925,Joni Blumstein,Consumer,Dublin,Ohio,...,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,19.7760,4,0.70,-13.84,0.79,Medium
1,6224,US-2011-144729,2011-07-21,24-07-2011,First Class,SS-20140,Saphhira Shifley,Corporate,San Miguelito,Panama,...,OFF-FA-10002247,Office Supplies,Fasteners,"Oic Paper Clips, Bulk Pack",11.5440,2,0.40,-5.22,0.97,Medium
2,15333,IT-2014-4749412,2014-09-18,23-09-2014,Standard Class,MB-18085,Mick Brown,Unknown,Birmingham,England,...,OFF-AR-10003113,Office Supplies,Art,"Binney & Smith Pens, Blue",29.8500,5,0.50,-4.80,3.71,Medium
3,49259,NI-2013-4420,2013-04-10,10/10/2013,Standard Class,MP-7965,Michael Paige,Corporate,Lagos,Lagos,...,OFF-AVE-10004512,Office Supplies,Binders,"Avery Hole Reinforcements, Economy",1.3230,1,0.70,-3.09,0.06,Medium
4,24199,IN-2014-14423,2014-10-29,30-10-2014,First Class,DL-12925,Daniel Lacy,Consumer,Kendari,Sulawesi Tenggara,...,FUR-FU-10002362,Furniture,Furnishings,"Advantus Door Stop, Black",131.4876,4,0.27,25.17,0.00,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51365,17526,ES-2014-2057259,2014-08-02,5/8/2014,First Class,PB-19150,Philip Brown,Consumer,Cagnes-Sur-Mer,Provence-Alpes-Cote D'Azur,...,OFF-PA-10002616,Office Supplies,Paper,"Green Bar Parchment Paper, Multicolor",108.5400,6,0.00,34.56,11.76,Medium
51366,36055,CA-2011-121573,2011-11-03,"Jul 11, 2011",Standard Class,SG-20605,Speros Goranitis,Consumer,New York City,New York,...,TEC-PH-10000984,Technology,Phones,Panasonic Kx-Tg9471B,783.9600,4,0.00,219.51,64.42,High
51367,43576,TU-2011-9190,2011-12-23,28-12-2011,Second Class,CM-1830,Cari Macintyre,Corporate,Corum,Corum,...,OFF-KIT-10002357,Office Supplies,Appliances,"Kitchenaid Blender, White",39.8400,1,0.60,-12.96,5.84,Medium
51368,22403,IN-2013-35388,2013-08-07,11/8/2013,Standard Class,IM-15055,Unknown,Consumer,Jakarta,Jakarta,...,OFF-AR-10000058,Office Supplies,Art,"Stanley Canvas, Water Color",38.4345,1,0.27,3.66,2.96,Medium
51369,12513,ES-2011-1222857,2011-09-30,2011-04-10,Standard Class,DP-13000,Darren Powers,Consumer,Toulouse,Midi-Pyrenees,...,FUR-CH-10003248,Furniture,Chairs,"Safco Bag Chairs, Black",169.2360,9,0.60,-182.03,17.34,High

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51370 entries, 0 to 51369
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51370 non-null  int64
 1   Order ID        51370 non-null  str
 2   Order Date      51370 non-null  datetime64[us]
 3   Ship Date       51370 non-null  str
 4   Ship Mode       51370 non-null  str
 5   Customer ID     51370 non-null  str
 6   Customer Name   51336 non-null  str
 7   Segment         51370 non-null  str
 8   City            51351 non-null  str
 9   State           51339 non-null  str
 10  Country         51370 non-null  str
 11  Postal Code     51370 non-null  int64
 12  Market          51370 non-null  str
 13  Region          51370 non-null  str
 14  Product ID      51370 non-null  str
 15  Category        51370 non-null  str
 16  Sub-Category    51370 non-null  str
 17  Product Name    51370 non-null  str
 18  Sales           51370 non-null  float64
 19  Quantity        51370 non-null  int64
 20  Discount        51370 non-null  float64
 21  Profit          51370 non-null  float64
 22  Shipping Cost   51370 non-null  float64
 23  Order Priority  51370 non-null  str
dtypes: datetime64[us](1), float64(4), int64(3), str(16)
memory usage: 9.4 MB

In [7]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

In [34]:
df.groupby(
    [
        df['Order Date'].dt.year.rename('Year'),
        df['Order Date'].dt.quarter.rename('Quarter'),
        df['Order Date'].dt.month.rename('Month')
    ]
)[[
    'Sales',
    'Quantity',
    'Discount',
    'Profit'
]].agg(
    Total_Sales = ('Sales','sum'),
    Total_Quantity = ('Quantity','sum'),
    Total_Discount = ('Discount','sum'),
    Total_Profit = ('Profit','sum')
                ).round(2).sort_values('Year')

                    Total_Sales  Total_Quantity  Total_Discount  Total_Profit
Year Quarter Month
2011 1       1        107236.58            1565           74.60       8990.02
             2         99584.12            1290           52.84      13316.94
             3        149148.53            1910           77.90      15554.38
     2       4        123240.17            2069           80.62      15673.65
             5        153503.64            2035           83.70      13684.18
             6        213167.71            3093          156.77      23848.08
     3       7        123463.50            1818           78.12       8083.63
             8        203519.58            2932          117.03      23022.77
             9        289949.95            3695          133.03      36782.33
     4       10       195831.49            2689          105.54      24514.55
             11       278066.95            3870          167.74      27238.85
             12       325930.94            4447          184.26      39811.22
2012 1       1        135140.32            1899           74.05      10045.94
             2        113699.47            1612           71.20      15343.47
             3        164031.23            2273          100.70      16691.69
     2       4        165443.77            2324           93.57      17427.34
             5        201516.25            2922          113.56      27485.93
             6        258578.01            3687          166.66      34494.14
     3       7        155031.83            2335           99.44      18968.60
             8        304041.39            3798          135.66      43618.74
             9        280693.95            4141          163.71      26101.69
     4       10       260348.40            3572          127.37      36314.39
             11       306074.46            4986          204.55      28885.64
             12       335713.48            4593          170.29      32779.79
2013 1       1        203887.10            2464           88.20      29375.16
             2        177366.18            2252           82.83      25573.01
             3        197963.23            2668          113.01      24393.53
     2       4        190105.50            2792          117.70      19598.93
             5        263675.59            3812          152.10      27673.63
             6        378058.17            5164          203.79      43970.36
     3       7        230160.15            3335          126.69      28860.14
             8        323749.69            4891          191.95      31873.06
             9        374361.95            5730          239.26      37436.96
     4       10       299171.28            3915          160.89      41553.34
             11       374078.87            5510          206.37      48588.12
             12       401836.11            5583          210.09      50253.17
2014 1       1        249319.91            3257          125.68      29610.75
             2        189131.13            2621          114.20      19203.88
             3        268287.32            3836          140.44      40806.84
     2       4        250444.15            3622          163.38      24043.22
             5        297082.34            4329          183.27      29645.23
             6        409928.26            5912          242.99      46333.23
     3       7        266624.48            3687          162.78      27510.41
             8        459382.29            5768          211.95      58370.48
             9        458947.33            6621          264.50      62305.57
     4       10       422315.11            5948          236.50      58284.73
             11       538245.49            7573          294.00      63283.18
             12       498179.37            7389          330.40      43370.66