In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv(r'C:\Users\Marcus\Desktop\python pandas\superstore_data\version_control\superstore_clean.csv')

df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,31518,CA-2012-169397,2012-12-24,27-12-2012,First Class,JB-15925,Joni Blumstein,Consumer,Dublin,Ohio,...,OFF-BI-10002852,Office Supplies,Binders,Ibico Standard Transparent Covers,19.7760,4,0.70,-13.84,0.79,Medium
1,6224,US-2011-144729,2011-07-21,24-07-2011,First Class,SS-20140,Saphhira Shifley,Corporate,San Miguelito,Panama,...,OFF-FA-10002247,Office Supplies,Fasteners,"Oic Paper Clips, Bulk Pack",11.5440,2,0.40,-5.22,0.97,Medium
2,15333,IT-2014-4749412,2014-09-18,23-09-2014,Standard Class,MB-18085,Mick Brown,Unknown,Birmingham,England,...,OFF-AR-10003113,Office Supplies,Art,"Binney & Smith Pens, Blue",29.8500,5,0.50,-4.80,3.71,Medium
3,49259,NI-2013-4420,2013-04-10,10/10/2013,Standard Class,MP-7965,Michael Paige,Corporate,Lagos,Lagos,...,OFF-AVE-10004512,Office Supplies,Binders,"Avery Hole Reinforcements, Economy",1.3230,1,0.70,-3.09,0.06,Medium
4,24199,IN-2014-14423,2014-10-29,30-10-2014,First Class,DL-12925,Daniel Lacy,Consumer,Kendari,Sulawesi Tenggara,...,FUR-FU-10002362,Furniture,Furnishings,"Advantus Door Stop, Black",131.4876,4,0.27,25.17,0.00,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51365,17526,ES-2014-2057259,2014-08-02,5/8/2014,First Class,PB-19150,Philip Brown,Consumer,Cagnes-Sur-Mer,Provence-Alpes-Cote D'Azur,...,OFF-PA-10002616,Office Supplies,Paper,"Green Bar Parchment Paper, Multicolor",108.5400,6,0.00,34.56,11.76,Medium
51366,36055,CA-2011-121573,2011-11-03,"Jul 11, 2011",Standard Class,SG-20605,Speros Goranitis,Consumer,New York City,New York,...,TEC-PH-10000984,Technology,Phones,Panasonic Kx-Tg9471B,783.9600,4,0.00,219.51,64.42,High
51367,43576,TU-2011-9190,2011-12-23,28-12-2011,Second Class,CM-1830,Cari Macintyre,Corporate,Corum,Corum,...,OFF-KIT-10002357,Office Supplies,Appliances,"Kitchenaid Blender, White",39.8400,1,0.60,-12.96,5.84,Medium
51368,22403,IN-2013-35388,2013-08-07,11/8/2013,Standard Class,IM-15055,Unknown,Consumer,Jakarta,Jakarta,...,OFF-AR-10000058,Office Supplies,Art,"Stanley Canvas, Water Color",38.4345,1,0.27,3.66,2.96,Medium
51369,12513,ES-2011-1222857,2011-09-30,2011-04-10,Standard Class,DP-13000,Darren Powers,Consumer,Toulouse,Midi-Pyrenees,...,FUR-CH-10003248,Furniture,Chairs,"Safco Bag Chairs, Black",169.2360,9,0.60,-182.03,17.34,High

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51370 entries, 0 to 51369
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51370 non-null  int64
 1   Order ID        51370 non-null  str
 2   Order Date      51370 non-null  str
 3   Ship Date       51370 non-null  str
 4   Ship Mode       51370 non-null  str
 5   Customer ID     51370 non-null  str
 6   Customer Name   51336 non-null  str
 7   Segment         51370 non-null  str
 8   City            51351 non-null  str
 9   State           51339 non-null  str
 10  Country         51370 non-null  str
 11  Postal Code     51370 non-null  int64
 12  Market          51370 non-null  str
 13  Region          51370 non-null  str
 14  Product ID      51370 non-null  str
 15  Category        51370 non-null  str
 16  Sub-Category    51370 non-null  str
 17  Product Name    51370 non-null  str
 18  Sales           51370 non-null  float64
 19  Quantity        51370 non-null  int64
 20  Discount        51370 non-null  float64
 21  Profit          51370 non-null  float64
 22  Shipping Cost   51370 non-null  float64
 23  Order Priority  51370 non-null  str
dtypes: float64(4), int64(3), str(17)
memory usage: 9.4 MB

In [5]:
df.groupby(
    'Product ID'
)[[
    'Sales',
    'Quantity',
    'Discount',
    'Profit'
]].agg(
    Total_Sales = ('Sales','sum'),
    Average_Sales = ('Sales','mean'),
    Minimum_Sales = ('Sales','min'),
    Maximum_Sales = ('Sales','max'),
	Sales_Standard_Deviation = ('Sales','std'),
    Number_of_Transaction = ('Sales','count'),

    Total_Units_Sold = ('Quantity','sum'),
    Average_Units_Sold = ('Quantity','mean'),
    Minimum_Quantity = ('Quantity','min'),
    Maximum_Quantity = ('Quantity','max'),
    Quantity_Standard_Deviation = ('Quantity','std'),

    Total_Discount = ('Discount','sum'),
    Average_Discount = ('Discount','mean'),
    Minimum_Discount = ('Discount','min'),
    Maximum_Discount = ('Discount','max'),
    Discount_Standard_Deviation = ('Discount','std'),

    Total_Profit = ('Profit','sum'),
    Average_Profit = ('Profit','mean'),
    Minimum_Profit = ('Profit','min'),
    Maximum_Profit = ('Profit','max'),
    Profit_Standard_Deviation = ('Profit','std')
).round(2).sort_values('Total_Sales', ascending=False).head(15)

,Total_Sales,Average_Sales,Minimum_Sales,Maximum_Sales,Sales_Standard_Deviation,Number_of_Transaction,Total_Units_Sold,Average_Units_Sold,Minimum_Quantity,Maximum_Quantity,...,Total_Discount,Average_Discount,Minimum_Discount,Maximum_Discount,Discount_Standard_Deviation,Total_Profit,Average_Profit,Minimum_Profit,Maximum_Profit,Profit_Standard_Deviation
Product ID,,,,,,,,,,,,,,,,,,,,,
TEC-CO-10004722,61599.82,12319.96,8399.98,17499.95,3520.93,5,20,4.00,3,5,...,0.60,0.12,0.0,0.40,0.18,25199.94,5039.99,1120.00,8399.98,2771.85
TEC-PH-10004664,30041.55,3004.15,1725.06,5175.17,1046.85,10,52,5.20,3,9,...,0.84,0.08,0.0,0.17,0.06,5455.96,545.60,306.66,919.97,200.96
OFF-BI-10003527,27453.38,2745.34,762.59,6354.95,1851.75,10,31,3.10,1,6,...,2.40,0.24,0.0,0.80,0.31,7753.04,775.30,-2287.78,3177.48,1561.76
FUR-CH-10002024,22851.95,2539.11,981.37,4416.17,1275.70,9,41,4.56,2,9,...,1.90,0.21,0.0,0.30,0.11,-140.20,-15.58,-630.88,700.98,391.51
TEC-MA-10002412,22638.48,22638.48,22638.48,22638.48,NaN,1,6,6.00,6,6,...,0.50,0.50,0.5,0.50,NaN,-1811.08,-1811.08,-1811.08,-1811.08,NaN
TEC-PH-10004823,22262.10,2023.83,636.06,5724.54,1366.74,11,39,3.55,1,9,...,0.85,0.08,0.0,0.40,0.13,8121.47,738.32,133.39,2461.32,631.93
FUR-CH-10000027,21329.73,1777.48,670.14,5049.00,1270.06,12,50,4.17,2,11,...,1.19,0.10,0.0,0.27,0.11,1363.23,113.60,-165.24,656.37,230.38
OFF-AP-10004512,21147.08,3021.01,511.62,7958.58,2657.14,7,38,5.43,1,14,...,0.30,0.04,0.0,0.10,0.05,10345.58,1477.94,227.37,3979.08,1338.35
FUR-TA-10001889,20730.76,1884.61,254.53,4626.15,1322.26,11,48,4.36,1,8,...,3.22,0.29,0.0,0.50,0.20,-2684.17,-244.02,-916.04,647.55,553.46
OFF-BI-10001359,19823.48,1802.13,538.19,4305.55,1032.48,11,37,3.36,1,6,...,3.30,0.30,0.0,0.80,0.35,2233.50,203.05,-1480.03,1453.12,1051.34
TEC-MA-10001127,19145.75,4786.44,770.85,8749.95,3715.10,4,17,4.25,3,5,...,0.50,0.12,0.0,0.50,0.25,3647.83,911.96,-944.99,2799.98,1881.82
OFF-BI-10000545,19024.50,2113.83,456.59,9892.74,2937.12,9,48,5.33,2,13,...,4.70,0.52,0.0,0.80,0.30,760.98,84.55,-1141.47,4946.37,1923.43
TEC-CO-10001449,18839.69,2354.96,959.98,5399.91,1463.97,8,38,4.75,2,9,...,1.60,0.20,0.0,0.40,0.15,6983.89,872.99,192.00,2591.96,822.61
TEC-PH-10001457,18717.00,2339.62,1058.25,5737.50,1548.38,8,30,3.75,2,9,...,0.27,0.03,0.0,0.17,0.07,1695.30,211.91,-76.53,630.99,217.19
FUR-BO-10004834,18387.00,2298.37,154.22,4404.90,1515.88,8,41,5.12,1,9,...,1.37,0.17,0.0,0.50,0.17,-428.20,-53.52,-1665.05,1013.13,752.42